<?php if(is_array($sustainers) && count($sustainers)) : ?>
    <h2>Friends of Swaggerdile!</h2>
    <?= $this->partial( 'swaggerdile/index/partial-profile-grid.phtml',
                        array('profiles' => $sustainers,
                              'pageSize' => 100000)) ?>
    <br />
    <br />
<?php endif ?>
<h2>Check out the awesome stuff people are making!</h2>
<?php if(empty($profiles)) : ?>
  <h2>...Or not!  Your search didn't find any profiles.  Sorry, try again!</h2>
<?php else: ?>
  <?= $this->partial( 'swaggerdile/index/partial-profile-grid.phtml',
                      array('profiles' => $profiles,
                            'pageSize' => $pageSize)) ?>
<?php endif ?>
<?php if(!$userIsAdult): ?>
    <br />
    <br />
    <div class="text-center">
        If you'd like to see more creators, and you are over 18, you can
        <a href="<?= $this->url('adult') ?>?returnUrl=<?= urlencode($this->url('browse')) ?>">
            click here to opt-in to see adult material</a>
    </div>
<?php endif ?>

<br />
<br />
<div class="text-center">
  <?php if($page != 0) : ?>
    <a class="btn btn-success btn-lg" href="<?= $this->url('browse') ?>?s=<?= urlencode($search)?>&p=<?= $page-1 ?>&o=<?= $order ?>&d=<?= $orderDirection ?>">&laquo; Previous</a>
  <?php endif ?>
  <?php if(count($profiles) > $pageSize) : ?>
    <a class="btn btn-success btn-lg" href="<?= $this->url('browse') ?>?s=<?= urlencode($search)?>&p=<?= $page+1 ?>&o=<?= $order ?>&d=<?= $orderDirection ?>">Next &raquo;</a>
  <?php endif ?>
</div>

