<p>Coming soon!</p>
<p>But for now, a few quick tips:</p>
<ul>
<li>Popout chat has more features, such as showing who's in the stream and all the moderator controls.  Click the little black square with an arrow pointing out of it on the small chat to pop out the pop-out chat.</li>
<li>Popout chat also gives you the private chat feature!</li>
<li>The zipper-faced smiley is to mute somebody so if they are bothering you, you will no longer see what they say.</li>
<li>The red thing is a ban button, only for chat moderators.</li>
<li>You can set your chat moderators on your stream settings page.  It's on the Chat tab.  You can also unban people there.</li>
</ul>

