<?php if(!empty($this->messages)) : ?>
    <div class="jumbotron text-center">
        <?php foreach($this->messages as $message) : ?>
            <p style="color: red;"><?= $message ?></p>
        <?php endforeach ?>
    </div>
<?php endif ?>
  

<div class="jumbotron">
<?php
    $form = $this->form;
    $form->prepare();

    // Configure form
    $form->setAttribute('action', $this->url('forgot-password'));
    $form->setAttribute('method', 'post');
    $form->setAttribute('role', 'form');

    echo $this->form()->openTag($form);
?>
    <?php if($returnUrl) : ?>
        <input type="hidden" name="return" value="<?= $returnUrl ?>" />
    <?php endif ?>
    <p>If you enter your username or email below, you will be emailed a link to reset
       your password.</p>

    <div class="form-group">
        <label for="username"><?= $form->get('username')->getOption('label') ?></label>
        <?= $this->formElement($form->get('username')->setAttribute('class', 'form-control')) ?>
        <?= $this->FormElementErrors($form->get('username')); ?>
    </div>
    <?= $this->formElement($form->get('act')->setAttribute('class', 'btn btn-default')) ?>

    <?= $this->form()->closeTag() ?>
    <p>&nbsp;</p>
</div>
