<div class="col-md-12 jumbotron text-center">
  <h3>Your first 30 days of streaming are free!  No need to pay up front!</h3>
  <h3>
    It is just $5 per month for a 10-viewer maximum stream, or
    $10 per month for unlimited viewers after your free unlimited
    viewer trial.
  </h3>
</div>
<div class="col-md-12 content-heading clearfix">
  <h1>Getting Started</h1>
  <hr />
</div>
<div class="col-md-12">
  <p>Tigerdile loves artists!  Streaming on this site is a great
     way to get noticed, because visitors to this site are specifically
     looking to watch artists.
  </p>
  <p>We have a few
     <a href="<?= $this->url('terms') ?>" target="_blank">
       content restrictions and rules
     </a>
     you should read before signing up.
  </p>
</div>
<div class="col-md-12 content-heading clearfix">
  <h2>Here's How!</h2>
  <hr />
</div>
<div class="col-md-8 col-xs-12 col-sm-12">
  <ol>
    <li><a href="<?= $this->url('signup') ?>" target="_blank">Register!</a>
        You need an account to stream.  It is free and easy!  And it
        makes sure your chat name is reserved.
    </li>
    <li><a href="<?= $this->url('login') ?>" target="_blank">Login!</a>
        Make sure you're logged in before continuing.
    </li>
    <li><a href="<?= $this->url('create-profile') ?>" target="_blank">
          Request approval!
        </a>
        <p>We don't make <strong>any</strong> judgements about your art or
           your skills; Tigerdile invites everyone of every skill level to
           participate!  Anyone can stream, including crafters and gamers.
        </p>
        <p>The purpose of the approval process is to make sure you
           understand the rules, and to give us a chance to say 'hi!'
           and make sure you have all the help you need to get started.
        </p>
        <p>Approval usually takes less than 1 hour if you submit the
           request between about 10 AM and 11 PM Eastern US Time.
           It takes, at most, 24 hours.
        </p>
    </li>
    <li><a href="<?= $this->url('setup') ?>" target="_blank">
          Set up your stream!
        </a>
        Once you get your approval, use our handy &quot;wizard&quot;
        to get your stream configured and to set up your software.
    </li>
  </ol>
</div>
<div class="col-md-4 hidden-sm hidden-xs">
  <img src="<?= $this->basePath('img/tigerdile-romance.jpg') ?>"
       class="pull-right" />
</div>
<div class="clearfix"></div>
