<div class="row text-center hidden-sm hidden-xs">
  <p>
    <!-- <img src="<?= $this->basePath('img/homecon/TD-Homecon-Ad-2017-e621.gif') ?>" /> -->
  </p>
  <h4>The 2018 HomeCon will be November 18 through 20.  Our theme is
     Steampunk!
  </h4>
</div>
<div class="row">
  <div class="col-md-12 content-heading">
    <h1>About HomeCon</h1>
    <hr />
  </div>
  <div class="col-md-12">
    <p>HomeCon is s a convention you can attend from your home!  It is
       a loosely organized streaming event with different artists coming
       on to do art for you, along with panels and other similar
       convention-like ideas!  It even has a theme which changes from
       year to year.
    </p>
    <p>
      It was started in the Fall of 2012 when site co-owner Caribou
      was unable to get to Midwest Fur Fest due to the travel expenses.
      She announced that she was going to have a HomeCon instead.
    </p>
    <p>
      The site's other owner, Tanabi, helped organize the event and the
      first HomeCon ran with Caribou, Michele Light, Flinters, and
      Genesis Whitmore as the initial participants.
    </p>
    <p>
      It started off as a one-off thing, and has since become an
      anticipated yearly event!
    </p>
    <p>
      <a href="https://www.furaffinity.net/user/temrin" target="_blank">Temrin</a>
      is the chief organizer of HomeCon these days and does much of the work
      and banner art.  She deserves a lot of the credit for what HomeCon
      is today, and is the driving force behind what it'll be tomorrow!
    </p>
  </div>
  <div class="col-md-12 content-heading">
    <h1>Event T-Shirt</h1>
    <hr />
  </div>
  <div class="col-md-12">
  </div>
</div>
<p>What con doesn't have a T-Shirt to commemorate it?  This year we are taking the aproach a little differently by reaching out to a tigerdile artist to create a design for us instead of a contest. This year's artist is coming soon!</p>
<p>You can find our Tigerdile and HomeCon t-shirts and other merchandise at the following links. All purchased help support Tigerdile and HomeCon!</p>
<p>
  <a href="https://www.redbubble.com/people/tigerdile" target="_blank"><img src="<?= $this->basePath('/img/homecon/Homecon-Redbubblebutton.png') ?>"/></a>
<a href="https://www.teepublic.com/user/tigerdile" target="_blank"><img src="<?= $this->basePath('/img/homecon/Homecon-Teepublicbutton.png') ?>" /></a>
</p>

 					
<div class="row">
  <div class="col-md-12 content-heading">
    <h1 class="text-center">Event Raffle</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-sm-6 col-xs-6">
    <h2 class="text-center">How to Enter</h2>
    <hr />
    <ul>
      <li>Stream for 1+ Hours during HomeCon
      </li>
    </ul>
    <p class="text-center">-or-</p>
    <ul>
      <li>Once a day, you can create/submit an image to us, using the
          provided color palette(s) coming soon!
      </li>
    </ul>
    <p class="text-center">Either way, you're entered to win!</p>
    <!--<p class="text-center"><a class="text-center" target="_blank" href="<?= $this->basePath('/img/homecon/palettelrg.jpg' ) ?>"><Img src="<?= $this->basePath('/img/homecon/palettesml.jpg' )?>" alt="" /></a></p>-->
  </div>
  <div class="col-md-4 hidden-sm hidden-xs">
    <img class="img-responsive center-block" src="<?= $this->basePath('img/homecon/tigerdilegraphic-PrizeSML.png') ?>" />
  </div>
  <div class="col-md-4 col-sm-6 col-xs-6">
    <h2 class="text-center">Prizes</h2>
    <hr />
    <p>A raffle winner will be chosen each day of HomeCon.</p>
    <p>Raffle winners will win 1 month of FREE Pro-Level Tigerdile
       streaming and potentially more, coming soon!
    </p>
<!--<p>This year, <a href="http://www.furaffinity.net/user/dragonfoxdemon/" target="_blank">DragonFoxDemon</a> is offering a full body digital sketch to one lucky raffle winner!  A sample of the sort of thing you'd win is here: <a href="http://www.furaffinity.net/full/23605755/" target="_blank">Sample Raffle Prize</a></p>
<p><a href="http://www.jarlidium.com/" target="_blank">Jarlidium</a> is offering up Volumes 1-3 of <a href="https://store.jarlidium.com/collections/endtown" target="_blank">Endtown</a><br/>"While a mutagenic plague is rampaging, the major powers start a war with disintegration weapons, reducing much of the world to fine dust in a matter of hours. When that dust settles, the surviving mutants find themselves pitted against the Topsiders: the remaining, unmutated humans who are trapped in their sealed bio-suits until the mutants are exterminated and the virus with them. For protection, the mutants gather into hidden communities. Endtown is the largest and best-hidden of those, but its very safety allows other problems to flourish..."</p>
 <p><a href="
http://www.furaffinity.net/user/temrin/" target="_blank">Temrin</a> is offering up a flat colored chibi to one lucky winner. Example <a href="http://www.furaffinity.net/view/19857486/" target="_blank">1</a>, <a href="http://www.furaffinity.net/view/16865850/" target="_blank">2</a> (Will not include shading. Can be Digital or Traditional however you will only recieve a digital copy.)</p>-->
  </div>
  <div class="col-md-6">
    <h2 class="text-center">Panel Submissions</h2>
    <hr />
    <ul>
      <li>Panels must be art/education related.</li>
      <li>Examples: Tutorials / How To's / Educational</li>
      <li>May be any rating, as long as it follows our Terms of Service.</li>
    </ul>
    <p>
      <strong>We are now accepting live commission/request art streams!</strong>
      Panels are educational time slots for others to come and learn
      about a technique or art practice. (Gaming streams and such are NOT considered panels.) If in doubt, ask!
    </p>
    <p class="text-center">
      <a href="https://docs.google.com/forms/d/e/1FAIpQLSeiaSSQaSAx4xG299fA44uS1u09bdcOvLXMI1QamuXicF1-6w/viewform" target="_blank"><img alt="Application" src="<?= $this->basePath('img/homecon/HomeCon-PanelButton.png') ?>" /></a>
    </p>
  </div>
  <div class="col-md-6">
    <h2 class="text-center">Banners and Fliers</h2>
    <hr />
    <h3>Fliers - Coming Soon!</h3>
    <h3>Ad Banners</h3>
    <!--<p>Copy and paste the code to put a 'Dile on your page!</p>
    <p class="text-center"><img src="<?= $this->basePath('img/homecon/TD-Homecon-Ad-2017-150x50-static.gif') ?>" /></p>
    <p class="text-center"><input class="form-control" readonly value="&lt;a href='https://www.tigerdile.com/homecon' target='_blank'&gt;&lt;img src='https://www.tigerdile.com<?= $this->basePath('img/homecon/TD-Homecon-Ad-2017-150x50-static.gif') ?>' width='150' height='50' /&gt;&lt;/a&gt;" type="text" /></p>
    <p class="text-center"><img src="<?= $this->basePath('img/homecon/TD-Homecon-Ad-2017-150x50.gif') ?>" /></p>
    <p class="text-center"><input class="form-control" readonly value="&lt;a href='https://www.tigerdile.com/homecon' target='_blank'&gt;&lt;img src='https://www.tigerdile.com<?= $this->basePath('img/homecon/TD-Homecon-Ad-2017-150x50.gif') ?>' width='150' height='50' /&gt;&lt;/a&gt;" type="text" /></p>
  --></div>
</div>
<div class="row">
  <div class="col-md-12 content-heading">
    <h1 class="text-center">Event Schedule</h1>
    <hr />
  </div>
  <div class="col-md-12 text-center">
    <iframe src="https://www.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=tanabi.org_nvbkf51o6h20e6j5bouvitspco%40group.calendar.google.com&amp;color=%23125A12&amp;ctz=America%2FNew_York&amp;dates=20171101%2F20171130" style=" border-width:0 " width="900" height="600" frameborder="0" scrolling="no"></iframe>
  </div>
</div>
