<div class="row">
  <div class="col-md-8">
    <div class="jumbotron">
      <h2 class="text-center">Welcome to Tigerdile!</h2>
      <h4 class="text-center">Professional Artist Streaming</h4>
      <h3 class="text-center">
        <a href="<?= $this->url('stream') ?>">View Streams</a>
      </h3>
    </div>
    <h2>Latest News</h2>
    <p>
      So Tigerdile is on a new server again.  The old one had a lot of packet loss problems,
      and then their DNS kept going on the fritz which would make Tigerdile's hostname
      unresolvable.
    </p>
    <p>
      Occasional packet loss I can understand.  But DNS failure on such a large scale is
      inexcusable; that should be highly available.  So we got rid of them and we're on
      a new host.  Nobody use Limestone Networks, ever.
    </p>
    <p>
      We are no longer accepting new streamers and we're starting to take down some pages
      as a result.  Additionally, we will be releasing the Tigerdile source code open source
      probably towards the end of Summer.  We want to make sure there's some reasonable
      documentation for it, first, and that it is reasonably workable.
    </p>
    <p>
      Speak up if there are any problems with the new server!
    </p>
    <p>
      -- The Tigerdile Staff
    </p>
  </div>
  <div class="col-md-4 text-center">
    <?= $this->ads('front') ?>
  </div>
</div>
