<div class="col-md-12 content-heading">
  <h1>Pricing</h1>
  <hr />
</div>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-body text-center">
        <h4>Trying to buy streaming for yourself or someone else?
            <a href="<?= $this->url('order') ?>">
             Click here!
            </a>
        </h4>
      </div>
    </div>
  </div>
</div>
<div class="col-md-4">
  <div class="panel panel-default panel-pricing">
    <div class="panel-heading text-center">
      <h3>$5 / Month</h3>
      <h4>10 Viewer Limit</h4>
      <h4><strong>No Ads In Your Stream!</strong></h4>
    </div>
    <div class="panel-body text-center">
      <h5>At this subscription level, you're allowed to have up to
          10 viewers at a time watching your stream.
      </h5>
      <h5>We're not jerks,
          though; if you occasionally go over, that's okay!  We use
          the honor system, and it's worked well for us for years
          now.  We trust you!
      </h5>
    </div>
  </div>
</div>
<div class="col-md-4">
  <div class="panel panel-default panel-pricing">
    <div class="panel-heading text-center">
      <h3>$10 / Month</h3>
      <h4>Unlimited Viewers</h4>
      <h4><strong>No Ads In Your Stream!</strong></h4>
    </div>
    <div class="panel-body text-center">
      <h5>You can have as many viewers as you want!  We consider this
          our &quot;professional&quot; level.
      </h5>
      <h5>You may use our re-broadcast feature to send your stream to
          to other stream services to increase your audience!
      </h5>
    </div>
  </div>
</div>
<div class="col-md-4">
  <div class="panel panel-default panel-pricing">
    <div class="panel-heading text-center">
      <h3>$40 / Month</h3>
      <h4>Unlimited Viewers + Perks!</h4>
      <h4><strong>No Ads In Your Stream!</strong></h4>
    </div>
    <div class="panel-body">
      <h5 class="text-center">
          This level is for people that really want to show Tigerdile some
          love!  Tigerdile will love you back with the following perks:
      </h5>
      <h5>
        <ul>
          <li>Free Tigerdile Tadpole Plush or Tigerdile Tote Bag
              (First purcahse only)
          </li>
          <li>Front page ad on Tigerdile's site</li>
          <li>Your stream appears at the top of the list (grouped with
              other $40/month streams)
          </li>
          <li>You can replace your stream listing name with an image
              banner!
          </li>
        </ul>
      </h5>
      <h5 class="text-center" >Also, you may use our re-broadcast feature to send your stream to
          an unlimited number of other stream services to increase your audience!
      </h5>
    </div>
  </div>
</div>
<div class="jumbotron col-md-12 text-center">
  <h2>
    All tiers come with our extremely helpful support!
  </h2>
  <h3>
    Let's face
    it; you can stream pretty much anywhere.  What you're paying for with
    Tigerdile is responsive support and as close to 100% up-time as possible.
  </h3>
  <h3>
    If streaming is a big part of your income, then this should be important
    to you!
  </h3>
  <h3>
    You get what you pay for with a free service; on Tigerdile, you're
    royalty!
  </h3>
</div>

<div class="col-md-12 content-heading">
  <h1>Why Isn't it Free?</h1>
  <hr />
</div>
<div class="col-md-12">
  <p>
    Streaming isn't cheap; it costs Tigerdile about $400.00 a month to
    keep the lights on, and then we have yearly fees for accounting,
    taxes, and other staying-operational stuff on top of that.
  </p>
  <p>
    If you're not making money with your stream, then Tigerdile may
    not be the best option for you; though believe us, we'd love to have
    you anyway!  But our target audience is people who make money with their
    streams.  And if you're making money with your streams, is it
    really fair to let someone else foot the bill?
  </p>
  <p>
    Our artists are our only source of income; we do not inject ads
    into your stream page, or into your video stream, ever.  That's
    rude, nobody likes it, and we're not doing it.  Ever.  The majority
    of Tigerdile's profits go right back into improving the service.
  </p>
  <p>
    Remember; Tigerdile is a business expense, and if you're streaming
    on Tigerdile as a professional artist, you can write off your Tigerdile
    fees!
  </p>
</div>
