<?php if($invalid): ?>
<div class="jumbotron">
    <p>Looks like your recovery link expired or you have followed an invalid
       link.  Feel free to contact <a href="<?= $this->url('support') ?>">Support</a>
       if you think this is in error.
    </p>
</div>
<?php else: ?>
<div class="jumbotron">
  <?php if(strlen($message)): ?>
    <h3 class="text-center"><?= $message ?></h3>
  <?php endif ?>
  <form method="post">
    <div class="form-group">
      <label for="newpassword">
        Please provide a new password.
      </label>
      <input class="form-control" type="password" name="newpassword" />
    </div>
    <div class="form-group">
      <label for="newpasswordagain">
        Type it again.  This time with feeling!
      </label>
      <input class="form-control" type="password" name="newpasswordagain" />
    </div>
    <input type="submit" name="act" value="Save" class="btn btn-default btn-lg" />
  </form>    
</div>
<?php endif ?>
