<div class="jumbotron">
  <h1>Terms of Use</h1>
  <p>Last updated: October 28, 2017</p>
  <p>
    Tigerdile is a dirty monster, but that doesn't stop him from wanting to
    keep his pad up to certain standards. No one likes a messy pad, after all.
    As such, he has composed some general house rules that he expects his
    artists and guests to follow.  Tigerdile and his staff expect you to
    agree to these terms as a member of this site.
  </p>
  <p>
    To put it in legal terms, by using this site, you're agreeing to
    the following terms of use.
  </p>
</div>
<div class="jumbotron">
  <ul>
     <li dir="ltr">
       No Hate:  Tigerdile hates haters.  This website is absolutely
       intolerant of intolerance.  We do not accept derogatory content
       whether done &quot;in fun&quot; or otherwise on this site.
       Everyone has bad days, but we expect you not to have it here.
       If you feel the need to express opinions that slander a group or
       person, please take it to one of the bazillion social media sites out
       there. We'll not be understanding and ban/dismiss with a free hand.
       This can be summed up as &quot;don't be a jerk&quot;, and
       we'll all be just fine. Oh yeah.</li>
  </ul>
  <ul>
     <li dir="ltr">
       No begging.  Tigerdile doesn't want his home to be your platform for
       woe.  If Tigerdile gets mail from your watchers saying you are trying
       to get people to pay your rent for you because you blew all your cash
       on cheap women and cheaper malt liquor, he'll question your motives
       for being on this site.  Be professional, please!
     </li>
  </ul>
  <ul>
     <li dir="ltr">
       No Harassment: Hey, Tigerdile's been known to chase a skirt or two,
       but even he's got his limits. Our streamers pay to support this site,
       and in their streams, their rule is law. Respect our streamers,
       respect their moderators, and if they call you out on being a jerk
       then leave them alone. Harassment of any kind will not be tolerated.
       You should also be polite to other viewers; harassing them isn't
       allowed, either.
     </li>
  </ul>
  <ul>
     <li dir="ltr">
       Artists gotta Art: This site is for artists, by artists, to help you
       reach your clients in a positive, friendly environment. This includes
       all kinds of art; sculpture, music, fursuit making -- Tigerdile digs
       it all. If you really really really want to pay to stream other
       things, like video games, you can, though. Some things may be too
       'copyright dangeorus' for the 'Dile, though, like a stream dedicated
       to full-screen rebroadcasting movies. That's just asking for trouble,
       which brings us to our next point...
     </li>
  </ul>
  <ul>
     <li dir="ltr">
       Keep it Legal: Tigerdile is open to all kinds of ... interesting ideas,
       but he also doesn't want to lose his license or have the coppers
       knocking on his door.  We ask that streamers keep their content and
       activities online legal.  Tigerdile loves consenting adults, and good
       clean (dirty) fun. There is no gray area here, so if you want to argue
       that it is legal in your state, but not someone else's, you are doing
       it wrong. We will not take responsibility for you and will gleefully
       turn over logs and material to the authorities if you are caught doing
       something unspeakable, so just don't go there.  Have a question about
       what is illegal?  Ask us. It is up to you to know the laws.
       (And Tigerdile doesn't mean illegal like driving a horse around in
       your backseat in Virginia, or whatever. You know what he's talking
       about.)
     </li>
  </ul>
  <ul>
     <li dir="ltr">
       Age Policy: Tigerdile hates when kids come in and take all his
       lollypops and put fingerprints on his Faberge eggs. You must be over
       18 to participate in anything 'Not Safe For Work' here.  Streamers may
       volunteer their streams as Safe For Work, and kiddies can hang out
       there; but anything past our age wall (the "I'm of legal age" button)
       is 18+ only. Also, all streamers MUST be 18 years old or older;
       Tigerdile hates when kids steal their parent's credit cards and cause
       him charge backs.
     </li>
     <li dir="ltr">
       Content Age Policy: As for content, cub art is strictly forbidden.
       If you cannot post it on FA, you cannot stream it here.
       IF YOU STREAM IS MARKED SAFE FOR WORK: Make sure to maintain
       standards appropriate for critters of all ages.
     </li>
  </ul>
  <ul>
     <li dir="ltr">
       No &quot;Performance Art&quot;: Tigerdile doesn't care what you told
       that guy the camera was for, but there will be no live, human adult
       streaming on this server.  In simpler terms, No Porn. We don't want
       to see your naked ape body, so please do not show us. Not even if you
       claim it as art. It's just dirty pictures to us. &nbsp;We're all about
       dirty animal people, but not dirty human people. Just no.
     </li>
  </ul>
  <ul>
     <li dir="ltr">
       No Refunds: Tigerdile doesn't believe in commitment, and doesn't want
       you to have to commit to him, ya dig? So we only charge for services
       rendered. That way, you only pay for the service if you like it and
       you want to keep using it. It's like paying your power bill; you pay
       after you receive service, not before. If for some reason you think
       you've been charged in error, though, feel free to email:
       support AT tigerdile DOT com.
     </li>
  </ul>
</div>
<div class="jumbotron">
  <h2>Privacy Policy</h2>
  <p>
    Tigerdile really doesn't want to know your life story, and wants to 
    collect as little information as possible.  What little information we
    do collect <strong>IS NEVER SOLD OR DISTRIBUTED TO ANYONE!</strong>
    Tigerdile's a scary monster and nobody wants to try and steal from him;
    all the same, we try to hold your information as securely as possible
    and we do not store credit card information.
  </p>
  <p>
    That being said, the Internet is a crazy place.  By using this site,
    you AGREE TO HOLD TIGREDILE, LLC HARMLESS for any data breaches, etc.
    Believe us, you won't get much if you sue us anyway.
  </p>
  <h3>What we may collect</h3>
  <ul>
    <li>Your billing name and address</li>
    <li>Your email</li>
    <li>
      Information you enter into our forms -- your Stream information,
      for instance.
    </li>
    <li>
      Information you type into our chat -- we don't keep logs, but it may
      linger in a buffer for a bit due to the nature of the technology we
      use.
    </li>
    <li>
      Typical anonymous information -- your IP address, what kind of browser
      you use, standard traffic statistic junk
    </li>
  </ul>
  <p>People under the age of 18 are only permitted in non-adult sections of
     the site.  No-one under the age of 18 may stream unless under direct
     adult supervision, with the stream account belonging to the adult.
  </p>
  <h3>How your information is used</h3>
  <p>
    For the most part this is obvious!  We only use your personal information
    for Tigerdile related services; our streams, chats, and other for-pay
    services.  We do not distribute, sell, or use your information for
    marketing in any capacity.
  </p>
  <p>
    We have never emailed our viewers and likely never will; however, if you
    are our customer (a streamer) we may send you news about our service.
    You can opt out of these emails at any time.
  </p>
  <h3>Disclosure to Third Parties</h3>
  <p>
   Tigerdile is a law-abiding monster.  If required by law via legal process
   or if compelled by government authority, your information may be turned
   over.  We don't wanna, but if you're using Tigerdile for bad stuff, we
   can't be responsible for what you do.
  </p>
  <p>
    Your billing information may be shared with our card processor for the
    purpose of charging your credit card.
  </p>
  <p>
    We never sell or otherwise disclose your information to a third party!
  </p>
  <h3>Questions?</h3>
  <p>
    Click our <a href="<?= $this->url('support') ?>">support link</a>,
    or email support AT tigerdile DOT com. 
  </p>
</div>
