<div class="row">
    <div class="col-md-3" id="profile-sidebar">
        <?php
            echo $this->partial('swaggerdile/admin/partial-dashboard-menu.phtml',
                                array('user' => $user));
        ?>
    </div>
    <div class="col-md-9">
        <p>Welcome to the Swaggerdile Admin Panel!</p>
        <p>If you're not supposed to be here, please be kind!</p>
    </div>
</div>
