<a href="<?= $this->url('dashboard') ?>" class="btn btn-default btn-lg" style="width: 100%">Back to Dashboard</a>
<a href="<?= $this->url('admin') ?>" class="btn btn-default btn-lg" style="width: 100%;">Admin Home</a>
<a href="<?= $this->url('admin', array('action' => 'payout')) ?>" class="btn btn-default btn-lg" style="width: 100%;">Payouts</a>

<p>Nothing below this line is finished yet.</p>
<a href="#" class="btn btn-default btn-lg" style="width: 100%;">Users</a>
<a href="#" class="btn btn-default btn-lg" style="width: 100%;">Approvals</a>
<a href="#" class="btn btn-default btn-lg" style="width: 100%;">Streams</a>
<a href="#" class="btn btn-default btn-lg" style="width: 100%;">Mailing</a>
<a href="#" class="btn btn-default btn-lg" style="width: 100%;">Reports</a>
