<?php
    // Useful variables
    $lowBandwidth = $settings['lowBandwidth'];
    $password = $settings['password'];
    $rtmpt = $settings['rtmpt'];

    // Add CSS
    $this->headLink()->appendStylesheet(
                        $this->basePath('video-js/video-js.css')
    );

    // Add JS
    $this->inlineScript()->appendFile(
                        $this->basePath('video-js/video.min.js')
    )->appendFile($this->basePath('video-js-libs/videojs-contrib-hls.min.js'))
     ->appendFile($this->basePath('js/bootstrap-toolkit.min.js'))
     ->appendFile($this->basePath('js/flv.min.js'))
     ->appendFile($this->basePath('js/td-video.js'))
     ->captureStart(); ?>
videojs.options.flash.swf = "<?= $this->basePath('video-js.swf') ?>";

jQuery(window).ready(function() {
    <?php if($lowBandwidth) : ?>
        var video = videojs('my_video', {html5: {hls: {withCredentials: true}}});
        video.volume(1);
        return;
    <?php endif ?>
    var video = tdvideo.loadVideo('my_video',
                                  <?php if(!$settings['forceFlash']) : ?>
                                      'https://outbound.tigerdile.com:8443/live/<?= $stream->getUrl() ?>.flv<?= strlen($password) ? '?stream_password=' . urlencode($password) : '' ?>'
                                  <?php else: ?>
                                      ''
                                  <?php endif ?>,
                                  <?php if(!$settings['forceFlashless']): ?>
                                      '<?= $rtmpt ? 'rtmpt' : 'rtmp' ?>://outbound.tigerdile.com/live/<?= $stream->getUrl() .  (strlen($password) ? '?stream_password=' . urlencode($password) : '') ?>'
                                  <?php else: ?>
                                      ''
                                  <?php endif ?>,
                                  <?php if(!$settings['forceFlash']) :?>
                                      'https://outbound.tigerdile.com/<?= $stream->getUrl() ?>/index.m3u8<?= (strlen($password) ? '?stream_password=' . urlencode($password) : '' ) ?>'
                                  <?php else: ?>
                                      ''
                                  <?php endif ?>, 1, true);
});

var channelId = <?= (int)$stream->getId() ?>;

function loadViewerCount() {
    jQuery.get('https://api.tigerdile.com/video?key=<?= $stream->getUrl() ?>',
               function(data) {
                   jQuery('#viewerCount').text(data[0]['viewers']);

                   var waitTime = Math.floor((Math.random()*10001)+5000);


                   setTimeout(loadViewerCount, waitTime);
               }, 'json'
    );
}

jQuery(document).ready(function() {
    loadViewerCount();

    jQuery('#popoutButton').click(function(ev) {

        <?php $settings['popout'] = 1; ?>
        window.open('<?= $this->url('stream/detail', array('stream' => $stream->getUrl()), array('query' => $settings)) ?>',
                    '_blank',
                    'height=' + jQuery('#my_video').height() +
                    ',menubar=0,location=0,resizable=1,scrollbars=0,status=0,toolbar=0,width=' +
                    jQuery('#my_video').width()
        );
        <?php $settings['popout'] = 0; ?>

        jQuery('#my_video').remove();
        ev.preventPropagation();
        return false;
    });

    jQuery('#favbutton').click(function(ev) {
        var img = jQuery(this).find('img');

        if(img.attr('src').endsWith("full.png")) {
            // delete it
            jQuery.ajax({
                async: true,
                url: '<?= $this->url('rest', array('action' => 'removefavorite')) ?>',
                data: {channelId: channelId},
                dataType: 'json',
                method: 'POST',
                success: function(data) {
                        if(data["status"]) {
                            img.attr('src', '<?= $this->basePath('img/starempty.png') ?>');
                        }
                    }
            });
        } else {
            jQuery.ajax({
                async: true,
                url: '<?= $this->url('rest', array('action' => 'addfavorite')) ?>',
                data: {channelId: channelId},
                dataType: 'json',
                method: 'POST',
                success: function(data) {
                        if(data["status"]) {
                            img.attr('src', '<?= $this->basePath('img/starfull.png') ?>');
                        }
                    }
            });
        }

        ev.preventDefault();
        return false;
    });

    jQuery('#sfw-toggle').click(function(ev) {
        ev.preventDefault();

        var ele = jQuery(this);

        jQuery.ajax({
            async: true,
            url: '<?= $this->url('rest', array('action' => 'setsfw')) ?>',
            data: {channelId: channelId, sfw: ele.attr('ref')},
            dataType: 'json',
            method: 'POST',
            success: function(data) {
                        if(data["status"]) {
                            if(ele.attr('ref') == "1") {
                                ele.text('SFW: ON');
                                ele.removeClass('btn-danger');
                                ele.addClass('btn-success');
                                ele.attr('ref', '0');
                            } else {
                                ele.text('SFW: OFF');
                                ele.addClass('btn-danger');
                                ele.removeClass('btn-success');
                                ele.attr('ref', '1');
                            }
                        }
                    }
        });

        return false;
    });
});

<?php
    $this->inlineScript()->captureEnd();


    $isLoggedIn = is_object($user);
    $isOwner = $isLoggedIn && ($stream->getOwnerId() == $user->getId());

    if(!$popout):
?>
  <style>
    div.video-controls-top .btn {
        height: 30px;
        line-height: 2;
    }

    .chat-wrapper{
        position:absolute;
        left:75%;
        top:0;
        right:0;
        bottom:0;
    }

    .chat-wrapper iframe{
        width:100%;
        height:100%;
    }

    @media screen and (max-width:991px){
        .chat-wrapper {
            position:relative;
            height:300px;
            width:100%;
            left:0;
            float: left;
        }
    }
  </style>
  <div class="row text-center">
    <div class="video-controls-top btn-group btn-group-xs" role="group" aria-label="Video Controls">
      <?php if($isLoggedIn && (!$isOwner)) : ?>
        <button type="button" class="btn btn-default" id="favbutton">
        <?php if($user->isSubscribed($stream->getId())) : ?>
          <img height="26" width="26" src="<?= $this->basePath('img/starfull.png') ?>" />
        <?php else: ?>
          <img height="26" width="26" src="<?= $this->basePath('img/starempty.png') ?>" />
        <?php endif ?>
        </button>
      <?php endif ?>
      <?php if($lowBandwidth): $settings['lowBandwidth'] = 0; ?>
        <a href="<?= $this->url('stream/detail', array('stream' => $stream->getUrl()), array('query' => $settings)) ?>" class="btn btn-default">Regular Bandwidth</a>
      <?php $settings['lowBandwidth'] = 1; else: $settings['lowBandwidth'] = 1; ?>
        <a href="<?= $this->url('stream/detail', array('stream' => $stream->getUrl()), array('query' => $settings)) ?>" class="btn btn-default">Low Bandwidth</a>
      <?php $settings['lowBandwidth'] = 0; endif ?>
      <?php if(!$lowBandwidth): // These don't apply for L.B. ?>
        <?php if($settings['forceFlash']): $settings['forceFlash'] = 0; $settings['forceFlashless'] = 0; ?>
          <a href="<?= $this->url('stream/detail', array('stream' => $stream->getUrl()), array('query' => $settings)) ?>" class="btn btn-info">Force Flash: On</a>
          <?php $settings['forceFlash'] = 0; $settings['forceFlashless'] = 1; ?>
          <a href="<?= $this->url('stream/detail', array('stream' => $stream->getUrl()), array('query' => $settings)) ?>" class="btn btn-default">Force Flashless: Off</a>
        <?php $settings['forceFlash'] = 1; $settings['forceFlashless'] = 0;
            elseif($settings['forceFlashless']): $settings['forceFlash'] = 1; $settings['forceFlashless'] = 0; ?>
          <a href="<?= $this->url('stream/detail', array('stream' => $stream->getUrl()), array('query' => $settings)) ?>" class="btn btn-default">Force Flash: Off</a>
          <?php $settings['forceFlash'] = 0; $settings['forceFlashless'] = 0; ?>
          <a href="<?= $this->url('stream/detail', array('stream' => $stream->getUrl()), array('query' => $settings)) ?>" class="btn btn-info">Force Flashless: On</a>
        <?php $settings['forceFlash'] = 0; $settings['forceFlashless'] = 1;
            else: $settings['forceFlash'] = 1; $settings['forceFlashless'] = 0; ?>
          <a href="<?= $this->url('stream/detail', array('stream' => $stream->getUrl()), array('query' => $settings)) ?>" class="btn btn-default">Force Flash: Off</a>
          <?php $settings['forceFlash'] = 0; $settings['forceFlashless'] = 1; ?>
          <a href="<?= $this->url('stream/detail', array('stream' => $stream->getUrl()), array('query' => $settings)) ?>" class="btn btn-default">Force Flashless: Off</a>
        <?php $settings['forceFlash'] = 0; $settings['forceFlashless'] = 0; endif ?>
        <?php if(!$settings['forceFlashless']): ?>
          <?php if($settings['rtmpt']): $settings['rtmpt'] = 0; ?>
            <a href="<?= $this->url('stream/detail', array('stream' => $stream->getUrl()), array('query' => $settings)) ?>" class="btn btn-info">Proxy Friendly Mode: On</a>
          <?php $settings['rtmpt'] = 1; else: $settings['rtmpt'] = 1; ?>
            <a href="<?= $this->url('stream/detail', array('stream' => $stream->getUrl()), array('query' => $settings)) ?>" class="btn btn-default">Proxy Friendly Mode: Off</a>
          <?php $settings['rtmpt'] = 0; endif; ?>
        <?php endif ?>
      <?php endif ?>
      <a href="#" class="btn btn-default" id="popoutButton">Popout Video</a>
      <a href="<?= $this->url('help') ?>" target="_blank" class="btn btn-default">Help!</a>
      
      <!-- Buttons for stream owners only -->
      <?php if($isOwner) : ?>
        <?php if($stream->getIsNsfw()) : ?>
          <a href="#" id="sfw-toggle" ref="1" class="btn btn-danger">SFW: OFF</a>
        <?php else: ?>
          <a href="#" id="sfw-toggle" ref="0" class="btn btn-success">SFW: ON</a>
        <?php endif ?>
        <a href="<?= $this->url('stream/detail/edit', array('stream' => $stream->getUrl())); ?>" class="btn btn-default"><span class="glyphicon glyphicon-cog"></span></a>
      <?php endif ?>
    </div>
  </div>
<?php endif ?>
  <div class="row video-row" style="position: relative;">
<?php
    if(($streamOffline = \Swaggerdile\Media::getStreamOfflineBackground($stream)) === false) {
        $streamOffline = $this->basePath('img/default-offline.jpg');
    }
?>
    <div class="<?= $popout ? 'col-md-12' : 'col-md-9 col-sm-12 col-xs-12' ?> no-padding">
<?php if($lowBandwidth): ?>
      <div>
        <img src="https://preview.tigerdile.com/<?= $stream->getUrl() ?>.jpg" id="imageTarget" class="img-responsive" />
      </div>
      <div class="<?= $popout ? 'col-md-12' : 'col-md-9 col-sm-12 col-xs-12' ?>">
        <audio id="my_video"
             class="video-js vjs-default-skin clear-both"
             controls
             autoplay
             width="100%"
             height="30"
             data-setup='{"techOrder": ["flash", "html5"], "html5": {"hls": {"withCredentials": true}} }'
        >
          <source src="https://outbound.tigerdile.com/<?= $stream->getUrl() ?>_audio/index.m3u8<?= (strlen($password) ? '?stream_password=' . urlencode($password) : '' ) ?>" type="application/x-mpegURL" />
        </audio>
      </div>
    <?php $this->inlineScript()->captureStart() ?>
        var url = jQuery('#imageTarget').attr('src');

        setInterval(function() {
            var now = new Date();
                jQuery('#imageTarget').attr('src', url + '?rand=' + now.getTime());
            }, 5000);
    <?php $this->inlineScript()->captureEnd() ?>
<?php else: ?>
    <div class="embed-responsive embed-responsive-<?= $stream->getAspectRatio() ? '16by9' : '4by3' ?>">
      <video id="my_video"
             class="video-js vjs-default-skin embed-responsive-item"
             controls
             autoplay
             poster="<?= $streamOffline ?>"
      ></video>
    </div>
<?php endif ?>
    </div>
    
        <?php if(!$popout) : ?>
      <div class="chat-wrapper">
        <iframe id="chatbox" class="chat" src="https://chat.tigerdile.com/?channelId=<?= $stream->getId() ?>&small=1<?= (strlen($password) ? '&stream_password=' . urlencode($password) : '' ) ?>"></iframe>
      </div>
      <?php if($lowBandwidth) : ?>
        </div>
      <?php endif ?>
    <?php endif ?>


  </div>
<?php if(!$popout): ?>
  <div class="row text-center">
    Viewer Count: <span id="viewerCount">Loading...</span>
  </div>
  <?php if(strlen($stream->getDonationEmail())) : ?>
    <div class="row text-center">
      <form method="post" action="https://donations.tanabi.com" target="_blank">
        <input type="hidden" name="email" value="<?= $stream->getDonationEmail() ?>" />
        <input type="hidden" name="name" value="<?= \Swaggerdile\Model\Factory::getInstance()->get('User')->fetchById($stream->getOwnerId())->getDisplayName() ?>" />
        <input type="hidden" name="token" value="<?= md5($stream->getDonationEmail() . TIGERDILE_DONATION_API_TOKEN) ?>" />
        <?php if(($donateButton = \Swaggerdile\Media::getStreamDonateButton($stream)) === false) : ?>
          <input type="submit" class="btn btn-default" name="act" value="Donate to <?= htmlentities($stream->getTitle()) ?>!" />
        <?php else: ?>
          <input type="image" src="<?= $donateButton ?>" alt="Donate!" />
        <?php endif ?>
      </form>
    </div>
  <?php endif ?>
<?php endif ?>
