<?php echo $this->doctype(); ?>
<html lang="en">
<?php
  $isLoggedIn = isset($user) && is_object($user);
?>
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Tigerdile Streaming'))->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
      ->appendName('viewport', 'width=device-width, initial-scale=1.0')
      ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/jquery-ui.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))  ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
      ->prependFile($this->basePath('js/bootstrap.min.js'))
      ->prependScript('jQuery.widget.bridge("uibutton", jQuery.ui.button); jQuery.widget.bridge("uitooltip", jQuery.ui.tooltip);')
      ->prependFile($this->basePath('js/jquery-ui.min.js'))
      ->prependFile($this->basePath('js/jquery.min.js'))
      ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
      ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
  </head>
  <body>
    <div class="container-fluid content-body">
      <?php echo $this->content; ?>
      <div class="clearfix"></div>
    </div> <!-- /container -->
    <?php echo $this->inlineScript() ?>

    <script>
      <!--
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-36382929-2', 'auto');
      ga('send', 'pageview');
      -->
    </script>
  </body>
</html>
