<div class="row">
    <div class="col-md-3" id="profile-sidebar">
        <?php
            echo $this->partial('swaggerdile/dashboard/partial-dashboard-menu.phtml',
                                array('user' => $user));
        ?>
    </div>
    <div class="col-md-9">
        <form method="post">
            <div class="form-group">
                <input type="submit" name="act" value="<?= $this->translate('Download') ?>" />
            </div>
        </form>

        <?php if(!count($report)) : ?>
            <h3><?= $this->translate('You have no declined payments.  Hooray!') ?></h3>
        <?php else: ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Declined Payment Report
                    </h3>
                </div>
                <div class="panel-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th><?= $this->translate('User') ?></th>
                                <th><?= $this->translate('Email') ?></th>
                                <th><?= $this->translate('Tier') ?></th>
                                <th><?= $this->translate('Pledge') ?></th>
                                <th><?= $this->translate('Joined') ?></th>
                                <th><?= $this->translate('Declined') ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($report as $line) : ?>
                                <tr>
                                    <td><?= htmlentities($line->getDisplayName()) ?></td>
                                    <td><?= htmlentities($line->getUserEmail()) ?></td>
                                    <td><?= htmlentities($line->getTierTitle()) ?></td>
                                    <td><?= number_format($line->getPayment(), 2) ?></td>
                                    <td><?= date('Y-m-d', strtotime($line->getCreated())) ?></td>
                                    <td><?= date('Y-m-d', strtotime($line->getDeclinedOn())) ?></td>
                                </tr>
                            <?php endforeach ?>
                        </tbody>
                    </table>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
