<?php
/*
 * MultistreamTable.php
 *
 * Auto-generated by modelBuild.py Model script
 *
 * @author sconley
 */

namespace Swaggerdile\Model;

class MultistreamTable extends ModelTable
{
    /*
     * Define our datastore table Kind
     *
     * @param string
     */
    protected $table = 'sd_multistream';

    /*
     * Fetch profiles associated with a given profile ID.
     *
     * @param Profiles|id   The source profile
     * @return list of Profiles
     */
    public function fetchAssociatedProfiles($profile)
    {
        if(is_object($profile)) {
            $profile = $profile->getId();
        }

        $rowset = $this->select(function($select) use ($profile) {
            $select->join(  'sd_profiles', 
                            'sd_profiles.id = sd_multistream.second_profile_id')
                   ->where(array('first_profile_id' => $profile));

            return $this->_addQueryFeatures($select);
        });

        return $this->_returnArray($rowset);
    }
}
