<?php
/*
 * Orders.php
 *
 * Auto-generated by modelBuild.py Model script
 *
 * @author sconley
 */

namespace Swaggerdile\Model;

class Orders extends Model
{
    /*
     * Cached order items
     *
     * @var array
     */
    protected $_orderItems = false;

    /*
     * Get order items associated with order.  This may be cached.
     *
     * @param integer Optional profile ID
     *
     * @return array of associated order items
     */
    public function getOrderItems($profileId = false)
    {
        if($this->_orderItems === false) {
            $orderItems = Factory::getInstance()->get('OrderItems');

            if($profileId === false) {
                $this->_orderItems = $orderItems->fetchByOrderId($this->getId());
            } else {
                $this->_orderItems = $orderItems->fetchByOrderIdAndProfileId($this->getId(), $profileId);
            }
        }

        return $this->_orderItems;
    }
}
