<?php
/*
 * PatreonValidateTable.php
 *
 * Auto-generated by modelBuild.py Model script
 *
 * @author sconley
 */

namespace Swaggerdile\Model;

use Zend\Db\Sql\Predicate\Expression;


class PatreonValidateTable extends ModelTable
{
    /*
     * Define our datastore table Kind
     *
     * @param string
     */
    protected $table = 'sd_patreon_validate';

    /*
     * This method generates a UUID in our database and returns it,
     * which is for validation purposes to ensure that a given
     * authentication code was sourced from our site.
     *
     * @param User user to generate token for
     * @param Profile profile ot link
     *
     * @return string
     */
    public function fetchNewId($user, $profile)
    {
        $this->insert(array(
            'validate_token' => new Expression('uuid()'),
            'user_id' => $user->getId(),
            'profile_id' => $profile->getId(),
        ));

        // get our new record
        $rowset = $this->select(array('id' => $this->getLastInsertValue()));

        // Delete old records
        $this->delete(function($delete) {
            $delete->where->lessThan('created', date('Y-m-d H:i:s',
                                                mktime(date('H')-1)));
            return $delete;
        });

        return $rowset->current()->validate_token;
    }
}
