<?php
/*
 * PayoutRequestsTable.php
 *
 * Auto-generated by modelBuild.py Model script
 *
 * @author sconley
 */

namespace Swaggerdile\Model;

class PayoutRequestsTable extends ModelTable
{
    /*
     * Define our datastore table Kind
     *
     * @param string
     */
    protected $table = 'sd_payout_requests';

    /*
     * Fetch outstanding payout requests
     *
     * @return array
     */
    public function fetchOutstandingRequests()
    {
        $rowset = $this->select(function($select) {
            $select->join('tigerd_users', 'tigerd_users.ID = sd_payout_requests.user_id',
                          array('display_name', 'user_email'))
                   ->join('tigerd_usermeta', 'tigerd_usermeta.user_id = sd_payout_requests.user_id',
                          array())
                   ->join('sd_payout_method_types', 'sd_payout_method_types.id = sd_payout_requests.type_id',
                          array('title'))
                   ->where(array(
                            'tigerd_usermeta.meta_key' => 'has_legal_docs',
                            'tigerd_usermeta.meta_value' => '1',
                            'sd_payout_requests.is_paid' => 0,
                        ));
            return $this->_addQueryFeatures($select);
        });

        return $this->_returnArray($rowset);
    }
}
