<?php
/*
 * ProfileUsers.php
 *
 * Auto-generated by modelBuild.py Model script
 *
 * @author sconley
 */

namespace Swaggerdile\Model;

class ProfileUsers extends Model
{
    /*
     * Profile user types
     */
    const MODERATOR = 1;
    const BANNED_USER = 2;
    const SUBSCRIBER = 3;
    const BANNED_SUBSCRIBER = 4;
    const FRIEND = 5;
}
