<?php
/*
 * Tiers.php
 *
 * Auto-generated by modelBuild.py Model script
 *
 * @author sconley
 */

namespace Swaggerdile\Model;

use Zend\Db\Sql\Sql;
use Zend\Db\Sql\Predicate\Literal;

class Tiers extends Model
{
    /*
     * Cache availability
     *
     * @var integer
     */
    protected $_availability = false;

    /*
     * Get a count of available slots in this tier.
     *
     * OR return false if there is no restriction.
     *
     * @return integer|false
     */
    public function getAvailability()
    {
        $max = (int)$this->getMaxAvailable();

        if(!$max) {
            return false;
        }

        if($this->_availability !== false) {
            return $this->_availability;
        }

        $sql = $this->_getSqlForTable('sd_subscriptions');

        $ret = $this->_sqlExecute($sql,
                $sql->select()
                    ->columns(array(new Literal('count(id) as total')))
                    ->where(array(
                        'tier_id' => $this->getId(),
                        'is_active' => 1,
                    ))
        );

        if(!count($ret)) {
            return $max;
        } else {
            $val = $ret->current();
            return ($max - (int)$val['total']);
        }
    }
}
