<div class="row">
    <div class="col-md-3" id="profile-sidebar">
        <?php
            echo $this->partial('swaggerdile/profile/partial-profile-menu.phtml',
                                array('isOwner' => $isOwner, 'editMode' => 0,
                                      'profile' => $profile, 'user' => $user,
                                      'subscriberTier' => $subscriberTier));
        ?>
    </div>
    <div class="col-md-9">
<?php
// Content listing!

if(!($numItems = count($content))) : ?>
    <div class="jumbotron text-center">
        <p>There's no content available for you to see yet!  Try again later.</p>
    </div>
<?php else: ?>
    <?php for($i = 0; ($i < $numItems) && ($i < $this->pageSize); $i++) :
            $post = $content[$i];
            $postUrl = $this->url('profile-posts',
                                           array(
                                            'profile' => $profile->getUrl(),
                                            'activity' => 'view',
                                            'param' => $post->getId(),
                                        ));
        ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $post->getTitle() ?></h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <?php
                        if(\Swaggerdile\Media::contentHasThumbnail($post)) : ?>
                            <div class="col-md-3">
                                <a href="<?= $postUrl ?>"><img class="img-responsive center-block" src="<?= $this->url('secure-thumbnail', array('profile' => $profile->getUrl(), 'activity' => $post->getId())) ?>" /></a>
                            </div>
                            <div class="col-md-9">
                        <?php else: ?>
                            <div class="col-md-12">
                        <?php endif ?>
                    <?php
                        $tagless = strip_tags($post->getContent());

                        if(strlen($tagless) > 300) : ?>
                        <p><?= substr($tagless, 0, 300) ?>&hellip;</p>
                    <?php else : ?>
                        <p><?= $tagless ?></p>
                    <?php endif ?>
                    <p><a href="<?= $postUrl ?>">View Post</a> - <small>Posted on <?= date('Y-m-d H:i:s', strtotime($post->getCreated())) ?></small></p>
                    </div>
                </div>
            </div>
        </div>
    <?php endfor ?>
    <div class="text-center">
          <?php if($page != 0) : ?>
            <a class="btn btn-success btn-lg" href="<?= $this->url('profile-posts', array('profile' => $profile->getUrl())) ?>?p=<?= $page-1 ?>&o=<?= $order ?>&d=<?= $orderDirection ?>">&laquo; Previous</a>
          <?php endif ?>
          <?php if($numItems > $pageSize) : ?>
            <a class="btn btn-success btn-lg" href="<?= $this->url('profile-posts', array('profile' => $profile->getUrl())) ?>?p=<?= $page+1 ?>&o=<?= $order ?>&d=<?= $orderDirection ?>">Next &raquo;</a>
          <?php endif ?>
    </div>


<?php endif ?>

    </div>
</div>
